### ISSUE TITLE
How can I compile the kgt adn libfsm under linux?

### ISSUE THREAD

**Issue by perlawk** [katef/kgt#1]
I failed to compiler the kgt and libfsm, both needed a pmake program. 
My archlinux system only have gnu make, bmake, no pmake, 
Can I compile the C source code manually without the makefile,
I cannot find the lexer .lx and parser .sid files program,
What parser and lexer generator are you used for this program. Thanks for your attention.

**Comment by katef** [comment]
Hi there, thank you for looking!

Usually I commit the generated source for things; I've done that for kgt now (in bb7bd47bbf1c68b70b070edfa8e816ba642aa3ac). So you shouldn't need the parser generator, SID.

However, you can get SID from http://www.tendra.org/ - it's in an svn repository there.

pmake is the ubtunu package name for bmake - I don't know why they named it pmake. It's the same program. These makefiles will work with any BSD-make dialect; pmake, bmake, nbmake, or whatever else it might be called. Arch linux's bmake is fine.

**Comment by katef** [comment]
@perlawk did you manage to get things compiled?

**Comment by perlawk** [comment]
I got everything compiled when a download the kmkf package and put the mk directory to
replace the link in kgt/share/mk, everything compile. Why the readme.md file never told the
user to install the mk files. It's good to give some hint to those not familiar it.

**Comment by katef** [comment]
Ah I see!

You shouldn't have to do that. I added cloning information in 2b1dac151bc3ece5b1cb3e73a11e4260e254730c

Thanks
