### ISSUE TITLE
Nearly all ebnf files failed to work?

### ISSUE THREAD

**Issue by perlawk** [katef/kgt#2]
in the example directory, I tried to use the ebnf format.
They are so inconsistent, some times need a ',', sometimes not necessary.
Only the json.ebnf can pass the generator.
the format: *ALPHA not work, need to use 0*ALPHA
1*4DIGIT not work at all, may be it means DIGIT{1,4} in perl re style.
=/ also not work.
The generation in rrtext:
{} and [] make no difference, only U and upsidedown U, I think there are some common bugs
that trigger all the format failed also. Sorry for so many complain.

**Comment by katef** [comment]
This is true - there are several different dialects, all of which people call "ebnf". Those examples are other people's various different things I've found, which (confusingly) all get called "ebnf".

I didn't want to implement parsers for dialects unless there is a clear specification to follow. I don't want to accidentally invent yet more dialects.

I think we should split the ebnf dialect into separate parsers:
* W3C's own EBNF: https://www.w3.org/TR/REC-xml/#sec-notation - this does not use semicolons, or commas between concatenated terms;
* BS EBNF: BS 6154 - (withdrawn) which does require a comma. Brief overview here: http://csci.csusb.edu/dick/cs320/comp.text.Meta.html#BS6154
* ISO/IEC 14977 : 1996(E) - there's a brief description of it here: https://www.cl.cam.ac.uk/~mgk25/iso-14977-paper.pdf

Then we could figure out which examples are supposed to be which dialect, and rename them accordingly.

**Comment by katef** [comment]
@perlawk which ebnf dialect would you like to use?

**Comment by katef** [comment]
Renamed the ebnf dialect to iso-ebnf in 94137d54dad119463a95404547dfdda876bda9d5. This is ISO/IEC 14977 : 1996(E).

[expr-minus.iso-ebnf](examples/expr-minus.iso-ebnf) and [json.iso-ebnf](examples/json.iso-ebnf) are the only examples in the ISO dialect. The other .ebnf examples are some other ebnf dialect.

Note ebnf2.ebnf is probably intended to be ISO EBNF, but technically incorrect; the standard requires an empty newline to separate productions. I imagine the author did not realise that, or have a way to validate it.

**Comment by katef** [comment]
I'm closing this because the EBNF dialect was split to multiple dialects. I'm sure there are bugs to fix for all of them.
