### ISSUE TITLE
Makefile missed DIR

### ISSUE THREAD

**Issue by perlawk** [katef/kgt#4]
The Makefile under the root of kgt, An instruction missed:
SUBDIR += src

DIR += ${BUILD}/lib // <- missed 

That make compile failed.
Thanks.

**Comment by katef** [comment]
Hiya,

How do you reproduce the error, please?

**Comment by perlawk** [comment]
Just download a fresh kgt-master.zip from github. Install the essential mk in share directory.
make or bmake in kgt-master.
some error:
ld -r -o build/lib/bnf.o build/src/bnf/lexer.o build/src/bnf/parser.o build/src/bnf/output.o 
ld: cannot open output file build/lib/bnf.o: No such file or directory

Because the makefile not create a build/lib directory, the bnf.o cannot be created.

**Comment by katef** [comment]
Can you reproduce this error when you check out the source by git recursively?
```
git clone --recursive git@github.com:katef/kgt.git
```

**Comment by perlawk** [comment]
when using git clone --recursive https://github.com/katef/kgt,
the error will disappear, so, some of the makefile in somewhere patched the hole.
I think it is not a very serious  bug. Only when someone just download the zip file without using the git, like browser only, will be compiled any more. The bug did not exist at my last download version. the old version makefile has this :
# TODO: centralise
#DIR += ${BUILD}/bin
DIR += ${BUILD}/lib
new makefile at the root no more,
I think some makefile make the directory build/lib for the bnf.o to save.
Sorry to make so much trouble.

**Comment by katef** [comment]
You're not making trouble! Thank you for the bug reports :)

I think I should document that downloading a .zip from github isn't suitable, because these repositories use submodules. I hadn't thought of people doing that at all, and I appreciate the feedback.

**Comment by katef** [comment]
I'm going to call this git's bug: https://github.com/dear-github/dear-github/issues/214
