### ISSUE TITLE
Makefile, needed to create directories

### ISSUE THREAD

**Issue by stevej098** [katef/kgt#54]
Great tool. thanks very much.
 "Just Worked" on MacOS 10.14 (Mojave) with clang and 'bsdmake' from Homebrew.

Only niggle is having to manually create subdirectories in BUILD dir.

build/src 
build/lib 
build/bin

Then all the 'SUBDIR' directories in kgt/Makefile

**Comment by stevej098** [comment]
Looking more...

share/mk is a symlink 

<subdir.mk> and <mkdir.mk> are included in the Makefile, but on MacOS with bsdmake, don't create the directories.

I wasn't able to track down the source of these two (duplicate) error messages:
"share/mk/mkdir.mk", line 36: warning: duplicate script for target "build/lib" ignored
"share/mk/mkdir.mk", line 36: warning: duplicate script for target "build/lib" ignored

By adding to Makefile an include <man.mk> and MAN ?= man/kgt.1 
I was able to get bsdmake to run the rules for target 'doc' (bsdmake doc)
but still fighting homebrew's XML / XSLT config

**Comment by katef** [comment]
Hi, thank you!

I don't have a macos system to hand. The makefiles definitely should be creating those subdirectories! Can you confirm the same problem still happens when you run `bsdmake -r` please?

**Comment by stevej098** [comment]
Understand that you're an individual with limited resources and Macs aren't everyone's platform.
Happy to help with any tests.

cloned the github repo again, then ran "bsdmake -r install"
- failed with build directory not there [unable to open output file 'build/src/ast.o': 'No such file or directory']

 Created all the subdirs by hand, "bsdmake -r install" ran to completion.

===========

iMac1:ast-posguy99 steve$ (cd ~/src; git clone --recursive https://github.com/katef/kgt.git)
Cloning into 'kgt'...
remote: Enumerating objects: 4393, done.
remote: Counting objects: 100% (84/84), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 4393 (delta 40), reused 42 (delta 18), pack-reused 4309
Receiving objects: 100% (4393/4393), 1.30 MiB | 3.34 MiB/s, done.
Resolving deltas: 100% (3337/3337), done.
Submodule 'share/git/kmkf' (https://github.com/katef/kmkf) registered for path 'share/git/kmkf'
Cloning into '/Users/steve/src/kgt/share/git/kmkf'...
remote: Enumerating objects: 819, done.        
remote: Counting objects: 100% (106/106), done.        
remote: Compressing objects: 100% (63/63), done.        
remote: Total 819 (delta 55), reused 83 (delta 37), pack-reused 713        
Receiving objects: 100% (819/819), 145.42 KiB | 4.15 MiB/s, done.
Resolving deltas: 100% (349/349), done.
Submodule path 'share/git/kmkf': checked out '8809bf65d44ef1686a6e686d5695874abd2cc17c'

iMac1:ast-posguy99 steve$ (cd ~/src/kgt; CC=clang; export CC; bsdmake -r install)
"share/mk/mkdir.mk", line 36: warning: duplicate script for target "build/lib" ignored
"share/mk/mkdir.mk", line 36: warning: duplicate script for target "build/lib" ignored
clang -o build/src/ast.o -ansi -pedantic -O3 -DNDEBUG -mmacosx-version-min=10.6  -c src/ast.c
error: unable to open output file 'build/src/ast.o': 'No such file or directory'
1 error generated.
*** Error code 1

Stop in /Users/steve/src/kgt.

iMac1:ast-posguy99 steve$ grep SUBDIR /Users/steve/src/kgt/Makefile | sed -e 's,SUBDIR += ,,' | grep -v -e '^src$' | while read dir; do mkdir -p ~/src/kgt/build/$dir;done

iMac1:ast-posguy99 steve$ mkdir -p ~/src/kgt/build/bin mkdir -p ~/src/kgt/build/lib

iMac1:ast-posguy99 steve$ (cd ~/src/kgt; CC=clang; export CC; bsdmake -r install)

[delete lots of output]

clang -M -o build/src/parsing_error.mk -MT build/src/parsing_error.o -ansi -pedantic  -c src/parsing_error.c
In file included from src/parsing_error.c:6:
src/parsing_error.h:30:8: warning: extra tokens at end of #endif directive [-Wextra-tokens]
#endif // KGT_PARSING_ERROR_H
       ^
1 warning generated.
clang -M -o build/src/rewrite_ci.mk -MT build/src/rewrite_ci.o -ansi -pedantic  -c src/rewrite_ci.c
clang -M -o build/src/rewrite_invisible.mk -MT build/src/rewrite_invisible.o -ansi -pedantic  -c src/rewrite_invisible.c
clang -M -o build/src/txt.mk -MT build/src/txt.o -ansi -pedantic  -c src/txt.c
clang -M -o build/src/xalloc.mk -MT build/src/xalloc.o -ansi -pedantic  -c src/xalloc.c
install -m 755 -d /usr/local/bin
install -m 755 build/bin/kgt /usr/local/bin/kgt

**Comment by stevej098** [comment]
This may not be a problem you can fix because a) bsdmake not your platform and b) MacOS testing outside scope - "Best Efforts" is acceptable, IMHO, for a small / niche project like yours.

your time is worth more working on code and real tests, not "farnarkling" on edge cases.

1. Add note in README or INSTALL doc that it's a known problem & MacOS users should be aware.
2. Provide a trivial script modelled on my 'grep SUBDIR' shell cmd (or a makefile / make target).
3. close issue with suitable comment

**Comment by katef** [comment]
I just pushed an update for the share/git/kmkf submodule; would you update that please? I don't _think_ the changes there are related, but I did address one issue in mkdir.mk and I'd like to have that at the current version just to be sure.

This stuff should work for bsdmake, don't worry, we'll get it working.

**Comment by stevej098** [comment]
I'm doing something wrong:
I can't see your changes, either in github via web or after I remove the repo and clone again.

I see a message about the submodule... Maybe that's correct.

While I've generally good command line skills, I'm new to 'git' and am having problems finding the magic incantations needed.
[pull didn't seem to work for me]

If you could tell me the command line that'll update the submodule, I'd appreciate that.
Otherwise, I've deleted my local copy of the repo and cloned it again.

using the github web interface, I can see three branches in the project.
"master" is 45 changes behind the default "main" branch.

I figure I named & cloned "main", but I still need to manually create the subdirs.

I'm not seeing "make clean" work either. Not an issue - related to me manually creating SUBDIRS.

In the bsdmake debug output, I can see where 'mkdir' is being called for dirs like 'build/src/wsn' from the makefile "share/mk/mkdir.mk".
there's a variable MKDIR set (with ?=), so I've tried setting that shell variable with the '-p' option.

Still no luck.

======

After a fresh clone, attempt at 'install'.

iMac1:ast-posguy99 steve$ (cd ~/src/kgt; MKDIR="/bin/mkdir -p "; export MKDIR; CC=clang; export CC; bsdmake -r install)
clang -o build/src/ast.o -ansi -pedantic -O3 -DNDEBUG -mmacosx-version-min=10.6  -c src/ast.c
error: unable to open output file 'build/src/ast.o': 'No such file or directory'
1 error generated.
*** Error code 1

Stop in /Users/steve/src/kgt.

======

Partial debug output, first match of 'mkdir' in log

Searching for mkdir.mk.../usr/local/Cellar/bsdmake/24/share/mk/bsdmake...share/mk...here...returning share/mk/mkdir.mk

Global:.MAKEFILE_LIST = Makefile share/mk/subdir.mk src/bnf/Makefile src/bnf/../../share/mk/top.mk .. .. src/blab/Makefile src/blab/../../share/mk/top.mk .. .. src/ebnfhtml5/Makefile src/ebnfhtml5/../../share/mk/top.mk .. .. src/dot/Makefile src/dot/../../share/mk/top.mk .. .. src/abnf/Makefile src/abnf/../../share/mk/top.mk .. .. src/iso-ebnf/Makefile src/iso-ebnf/../../share/mk/top.mk .. .. src/rbnf/Makefile src/rbnf/../../share/mk/top.mk .. .. src/sid/Makefile src/sid/../../share/mk/top.mk .. .. src/wsn/Makefile src/wsn/../../share/mk/top.mk .. .. src/rrd/Makefile src/rrd/../../share/mk/top.mk .. .. src/rrdump/Makefile src/rrdump/../../share/mk/top.mk .. .. src/rrtdump/Makefile src/rrtdump/../../share/mk/top.mk .. .. src/rrparcon/Makefile src/rrparcon/../../share/mk/top.mk .. .. src/rrll/Makefile src/rrll/../../share/mk/top.mk .. .. src/rrta/Makefile src/rrta/../../share/mk/top.mk .. .. src/rrtext/Makefile src/rrtext/../../share/mk/top.mk .. .. src/rrdot/Makefile src/rrdot/../../share/mk/top.mk .. .. src/svg/Makefile src/svg/../../share/mk/top.mk .. .. src/html5/Makefile src/html5/../../share/mk/top.mk .. .. src/json/Makefile src/json/../../share/mk/top.mk .. .. src/Makefile src/../share/mk/top.mk .. .. .. share/mk/sid.mk .. share/mk/lx.mk .. share/mk/obj.mk .. share/mk/dep.mk .. share/mk/ar.mk .. share/mk/so.mk .. share/mk/part.mk .. share/mk/prog.mk .. share/mk/mkdir.mk

Global:DIR = build/bin build/lib build/src build/src/abnf build/src/blab build/src/bnf build/src/dot build/src/ebnfhtml5 build/src/html5 build/src/iso-ebnf build/src/json build/src/rbnf build/src/rrd build/src/rrdot build/src/rrdump build/src/rrll build/src/rrparcon build/src/rrta build/src/rrtdump build/src/rrtext build/src/sid build/src/svg build/src/wsn

For: Iterator dir List build build/bin build/lib build/src build/src/abnf build/src/blab build/src/bnf build/src/dot build/src/ebnfhtml5 build/src/html5 build/src/iso-ebnf build/src/json build/src/rbnf build/src/rrd build/src/rrdot build/src/rrdump build/src/rrll build/src/rrparcon build/src/rrta build/src/rrtdump build/src/rrtext build/src/sid build/src/svg build/src/wsn

For: end for 1
Global:dir = build/src/wsn
Global:dir = build/src/wsn

--- dir = build/src/wsn
.if !exists(build/src/wsn)
mkdir:: build/src/wsn
.endif

---- at line 23
Global:delete dir
Global:dir = build/src/svg
Global:dir = build/src/svg
--- dir = build/src/svg
.if !exists(build/src/svg)
mkdir:: build/src/svg
.endif

======

Make target 'clean' after a successful build/install

 (cd ~/src/kgt; CC=clang; export CC; bsdmake -r clean)
[ delete lines] 
rmdir: build/src: Directory not empty
*** Error code 1

Stop in /Users/steve/src/kgt

All the SUBDIRs I manually created remain... 

iMac1:ast-posguy99 steve$ ls ~/src/kgt/build/src
abnf		bnf		ebnfhtml5	iso-ebnf	rbnf		rrdot		rrll		rrta		rrtext		svg
blab		dot		html5		json		rrd		rrdump		rrparcon	rrtdump		sid		wsn


======

What seemed the obvious "pull" request

iMac1:ast-posguy99 steve$ (cd ~/src/kgt; git pull )
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 4 (delta 1), reused 4 (delta 1), pack-reused 0
Unpacking objects: 100% (4/4), 441 bytes | 220.00 KiB/s, done.
From https://github.com/katef/kgt
   72222bf..b2c4209  main       -> origin/main
Updating 72222bf..b2c4209
Fast-forward
 share/git/kmkf | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

iMac1:ast-posguy99 steve$ (cd ~/src/kgt; CC=clang; export CC; bsdmake -r install)
"share/mk/mkdir.mk", line 36: warning: duplicate script for target "build/lib" ignored
"share/mk/mkdir.mk", line 36: warning: duplicate script for target "build/lib" ignored
install -m 755 -d /usr/local/bin
install -m 755 build/bin/kgt /usr/local/bin/kgt

======

Brute Force & Ignorance approach. Blow away dir and clone repo again. Named branch 'main', even though default.

 (cd ~/src; rm -rf kgt; \
    git clone -b main --recursive https://github.com/katef/kgt.git; \
   echo; ls -ltr | tail -1; echo; \
   cd kgt; CC=clang; export CC; bsdmake -r install )

Cloning into 'kgt'...
remote: Enumerating objects: 4397, done.
remote: Counting objects: 100% (88/88), done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 4397 (delta 41), reused 46 (delta 19), pack-reused 4309
Receiving objects: 100% (4397/4397), 1.30 MiB | 1.13 MiB/s, done.
Resolving deltas: 100% (3338/3338), done.

Submodule 'share/git/kmkf' (https://github.com/katef/kmkf) registered for path 'share/git/kmkf'

Cloning into '/Users/steve/src/kgt/share/git/kmkf'...
remote: Enumerating objects: 819, done.        
remote: Counting objects: 100% (106/106), done.        
remote: Compressing objects: 100% (63/63), done.        
remote: Total 819 (delta 55), reused 83 (delta 37), pack-reused 713        
Receiving objects: 100% (819/819), 145.42 KiB | 3.93 MiB/s, done.
Resolving deltas: 100% (349/349), done.

Submodule path 'share/git/kmkf': checked out '118ea1fb076ab5706122f47be06a3b3535596f71'

drwxr-xr-x   15 steve  staff        480 11 Sep 16:39 kgt

clang -o build/src/ast.o -ansi -pedantic -O3 -DNDEBUG -mmacosx-version-min=10.6  -c src/ast.c
error: unable to open output file 'build/src/ast.o': 'No such file or directory'
1 error generated.
*** Error code 1

Stop in /Users/steve/src/kgt.

======

Manually create dirs, then run install.
clang throwing warnings from '//' comment, but runs to completion.

iMac1:ast-posguy99 steve$ grep SUBDIR /Users/steve/src/kgt/Makefile | sed -e 's,SUBDIR += ,,' | grep -v -e '^src$' | while read dir; do mkdir -p ~/src/kgt/build/$dir;done; mkdir -p ~/src/kgt/build/bin mkdir -p ~/src/kgt/build/lib

(cd ~/src/kgt; CC=clang; export CC; bsdmake -r install) 

clang -o build/src/ast.o -ansi -pedantic -O3 -DNDEBUG -mmacosx-version-min=10.6  -c src/ast.c
clang -o build/src/ast_binary.o -ansi -pedantic -O3 -DNDEBUG -mmacosx-version-min=10.6  -c src/ast_binary.c
clang -o build/src/bitmap.o -ansi -pedantic -O3 -DNDEBUG -mmacosx-version-min=10.6  -c src/bitmap.c
clang -o build/src/main.o -ansi -pedantic -O3 -DNDEBUG -mmacosx-version-min=10.6  -c src/main.c
In file included from src/main.c:19:
src/parsing_error.h:30:8: warning: // comments are not allowed in this language [-Wcomment]
#endif // KGT_PARSING_ERROR_H
       ^
src/main.c:202:17: warning: ISO C90 forbids mixing declarations and code [-Wdeclaration-after-statement]
                parsing_error error;
                              ^
src/main.c:196:22: warning: ISO C90 forbids mixing declarations and code [-Wdeclaration-after-statement]
        parsing_error_queue errors = NULL;
                            ^
3 warnings generated.

[ delete lots ]

1 warning generated.
clang -M -o build/src/parsing_error.mk -MT build/src/parsing_error.o -ansi -pedantic  -c src/parsing_error.c
In file included from src/parsing_error.c:6:
src/parsing_error.h:30:8: warning: extra tokens at end of #endif directive [-Wextra-tokens]
#endif // KGT_PARSING_ERROR_H
       ^
1 warning generated.
clang -M -o build/src/rewrite_ci.mk -MT build/src/rewrite_ci.o -ansi -pedantic  -c src/rewrite_ci.c
clang -M -o build/src/rewrite_invisible.mk -MT build/src/rewrite_invisible.o -ansi -pedantic  -c src/rewrite_invisible.c
clang -M -o build/src/txt.mk -MT build/src/txt.o -ansi -pedantic  -c src/txt.c
clang -M -o build/src/xalloc.mk -MT build/src/xalloc.o -ansi -pedantic  -c src/xalloc.c
install -m 755 -d /usr/local/bin
install -m 755 build/bin/kgt /usr/local/bin/kgt

======

**Comment by katef** [comment]
Thanks. What's the output of `bsdmake -r -V '${DIR}'` please?

**Comment by stevej098** [comment]
(cd ~/src/kgt;  bsdmake -r -V '${DIR}' )

==> returns empty / null

**Comment by katef** [comment]
I'm very confused!

Would you mind installing bmake by hand from here please? http://www.crufty.net/help/sjg/bmake.html
(just bmake.tar.gz, not mk.tar.gz)

and then try `bmake -r install` per usual.

the bsdmake package you're using is a much older version of that, and I wonder if this problem is due to some difference between them. I'd really like to understand what's happening here.

**Comment by stevej098** [comment]
bmake worked in making 'kgt' with an "however" [note later, making 'bmake' a bit off]

I ran the following command line and it ran to completion, throwing many fewer warnings as well [full list attached]

(cd ~/src; rm -rf kgt; git clone -b main --recursive https://github.com/katef/kgt.git; \
cd kgt; CC=clang; export CC; bmake -r install )


===========

[compiler warnings]

src/parsing_error.c:36:31: warning: ISO C90 forbids mixing declarations and code [-Wdeclaration-after-statement]
        parsing_error_queue_element *head = *queue;

src/rewrite_ci.c:121:6: warning: ISO C90 forbids mixing declarations and code [-Wdeclaration-after-statement]
        int success = permute_cases(term->invisible, &term->u.group, &tmp);
            ^
src/rewrite_ci.c:151:1: warning: control may reach end of non-void function [-Wreturn-type]
}

src/rrd/tnode.c:210:1: warning: control may reach end of non-void function [-Wreturn-type]
}

===========

"However" building bmake has issues on MacOS.
 An initial 'make' fails with a shell infinite recursion (ie "fork: Resource temporarily unavailable"), 
but a later "make-bootstrap" works. 
Not your problem, left here as a breadcrumb for anyone else who gets this error.

===========

results of your previous test:

iMac1:ast-posguy99 steve$ (cd ~/src/kgt;  bsdmake -r -V '${DIR}' )
[empty]

iMac1:ast-posguy99 steve$ (cd ~/src/kgt;  bmake -r -V '${DIR}' )
build/bin build/lib build/src build/src/abnf build/src/blab build/src/bnf build/src/dot build/src/ebnfhtml5 build/src/html5 build/src/iso-ebnf build/src/json build/src/rbnf build/src/rrd build/src/rrdot build/src/rrdump build/src/rrll build/src/rrparcon build/src/rrta build/src/rrtdump build/src/rrtext build/src/sid build/src/svg build/src/wsn

**Comment by stevej098** [comment]
homebrew's "bsdmake" comes from Apple and is old, from 2005 as best I can determine

https://opensource.apple.com/source/bsdmake/

I couldn't see a way to discover the version / edition of bsdmake, no command line option I could see.

bsdmake-24 seems newest, but the man page for both -24 and -23 are both dated 14 October 2005

RCS-style "ident" strings are in there:

     $FreeBSD: src/usr.bin/make/arch.c,v 1.66 2005/05/24 15:58:34 harti Exp $
     $FreeBSD: src/usr.bin/make/buf.c,v 1.36 2005/05/13 08:53:00 harti Exp $
     $FreeBSD: src/usr.bin/make/cond.c,v 1.54 2005/05/25 16:06:14 harti Exp $
     $FreeBSD: src/usr.bin/make/dir.c,v 1.52 2005/03/23 12:56:15 harti Exp $
     $FreeBSD: src/usr.bin/make/for.c,v 1.43 2005/05/10 12:02:15 harti Exp $
     $FreeBSD: src/usr.bin/make/hash.c,v 1.25 2005/05/13 08:53:00 harti Exp $
     $FreeBSD: src/usr.bin/make/job.c,v 1.124 2005/10/09 06:36:51 scottl Exp $
     $FreeBSD: src/usr.bin/make/main.c,v 1.159 2005/12/05 14:22:12 ru Exp $
     $FreeBSD: src/usr.bin/make/make.c,v 1.38 2005/05/24 16:05:51 harti Exp $
     $FreeBSD: src/usr.bin/make/parse.c,v 1.110 2005/10/17 15:56:26 ru Exp $
     $FreeBSD: src/usr.bin/make/proc.c,v 1.1 2005/05/24 15:41:34 harti Exp $
     $FreeBSD: src/usr.bin/make/shell.c,v 1.1 2005/05/24 15:30:03 harti Exp $
     $FreeBSD: src/usr.bin/make/str.c,v 1.45 2005/05/23 13:27:52 harti Exp $
     $FreeBSD: src/usr.bin/make/suff.c,v 1.64 2005/05/24 15:58:35 harti Exp $
     $FreeBSD: src/usr.bin/make/targ.c,v 1.41 2005/05/13 13:47:41 harti Exp $
     $FreeBSD: src/usr.bin/make/util.c,v 1.19 2005/05/13 13:47:41 harti Exp $
     $FreeBSD: src/usr.bin/make/var.c,v 1.162 2006/04/08 07:02:39 fjoe Exp $

**Comment by sauclovian** [comment]
Also possibly relevant: https://gnats.netbsd.org/55542

**Comment by katef** [comment]
I talked with David Holland (@sauclovian) in the netbsd thread you linked there (he's the maintainer of upstream bmake), and @nilium helped investigate this. We think we've narrowed it down to a bug in `.WAIT` for bsdmake, and David thinks that's specifically for `::` rules.

We found we could work around this issue by rephrasing the `.WAIT`s here in the top-level Makefile:
```
all::  mkdir .WAIT dep .WAIT prog
```
either by adding `mkdir` to `dep`'s (and I guess `prog`'s) dependencies, or by splitting up the rule:
```
all::  mkdir
all:: .WAIT dep
all:: .WAIT prog
```

I suspect splitting it up this way works by coincidence of the order of execution, rather than `.WAIT` actually working. But I'm not sure how to test that.

Also not sure what I want the fix to be.

**Comment by sauclovian** [comment]
_a_ maintainer, not _the_ maintainer... anyway, to see if it works by accident try it with a few large values of -j, like -j 100.

For me with reasonably current bmake it works only the first way (all on one line), at least with the following simple version.
(ffs github, I can upload docx files but not a simple makefile without calling it .txt? and then nobody can see the file without downloading it? what's the point?)

    all: foo

    mkdir:
            @echo $@ IN
            @sleep 1
            @echo $@ OUT

    dep:
            @echo $@ IN
            @sleep 1
            @echo $@ OUT

    prog:
            @echo $@ IN
            @sleep 1
            @echo $@ OUT

    foo:: mkdir .WAIT dep .WAIT prog

    #foo:: mkdir 
    #foo:: .WAIT dep
    #foo:: .WAIT prog

    #foo:: mkdir .WAIT
    #foo:: dep .WAIT
    #foo:: prog

You'll need to fix the tabs in that after pasting it from here, of course.

**Comment by stevej098** [comment]
'bmake' works without adjusting anything, 'bsdmake' on MacOS / Homebrew is broken IMHO.
The simplest / best resolution is to change the README: "The MacOS bsdmake doesn't work for kgt: get bmake".

====

This isn't a problem with "-j", parallel processing. Using the '-B' flag, forces 'backwards compatibility' - one shell per command, everything in sequence - doesn't change behaviour.
I also removed the .WAIT from the Makefile, without change of behaviour.

====

The syntax to dump variable is different to 'bmake', don't need to wrap variables in ${..}.
The full directory list to be made is correct.

 steve$ (export MKDIR='mkdir -p'; export CC=clang; cd ~/src/kgt; bsdmake -B -r dep -V 'MKDIR' -V 'CC' -V 'DIR')
mkdir -p
clang
build/bin build/lib build/src build/src/abnf build/src/blab build/src/bnf build/src/dot build/src/ebnfhtml5 build/src/html5 build/src/iso-ebnf build/src/json build/src/rbnf build/src/rrd build/src/rrdot build/src/rrdump build/src/rrll build/src/rrparcon build/src/rrta build/src/rrtdump build/src/rrtext build/src/sid build/src/svg build/src/wsn

====

This is a problem with Apple's "bsdmake" which Homebrew package/distribute.
You can see from this file that it's a 2005 copy of FreeBSD make:
    https://opensource.apple.com/source/bsdmake/bsdmake-24/bsdmake.plist.auto.html

I wasn't able to find anything that described all the targets suppored. Not in man page or tutorial that I could see.

====

I've attached debugging output below + extract of man page with meaning of debug flags.
[bsdmake-debug-flags.txt](https://github.com/katef/kgt/files/7158879/bsdmake-debug-flags.txt)

Even though I asked for the target 'dep' from .include "share/git/kmkf/share/mk/dep.mk"
and can see the .mk file processed and '${MKDIR} directory' commands being built,
the end result is:
 - doesn't find the target 'dep',
 - doesn't run the mkdir commands
 - proceeds to attempt to compile the first .c file, as if it's running the default 'install'

====

Debugging Commands run:

(export MKDIR='mkdir -p'; export CC=clang; cd ~/src/kgt; bsdmake -dA -B -r dep 2>&1 ) >kgt-bsdmake-dA
(export MKDIR='mkdir -p'; export CC=clang; cd ~/src/kgt; bsdmake -dcdflmtv -B -r dep 2>&1 ) >kgt-bsdmake-dcdflmtv

[kgt-bsdmake-dcdflmtv.txt](https://github.com/katef/kgt/files/7158853/kgt-bsdmake-dcdflmtv.txt)
[kgt-bsdmake-dA.txt](https://github.com/katef/kgt/files/7158856/kgt-bsdmake-dA.txt)

**Comment by sauclovian** [comment]
Probably the right approach is to get homebrew to ship something like a current version.

**Comment by stevej098** [comment]
My bad, this was a "Problem between Screen & Keyboard"
 - not with bsdmake, it doesn't work, but with Homebrew / bmake.

I only tried 'bsdmake' because I, wrongly, thought there was no bmake in Homebrew.
I'd searched for 'bmake' didn't notice it in the long list returned :(

Please note in the README: 
"bsdmain on MacOS / Homebrew won't run kgt Makefiles, install bmake with 'brew install bmake', then run 'bmake -r install'"

The version of bmake on Homebrew is one version behind (20200902 vs 20210808)
https://formulae.brew.sh/formula/bmake 

I've attempted to raise an issue about this on Homebrew's github page.
