### ISSUE TITLE
Compilation instructions.

### ISSUE THREAD

**Issue by StyXman** [katef/kgt#55]
Running on Debian Unstable, GNU Make 4.3, I get this:

```
mdione@diablo:~/src/projects/kartozan/take2/kgt$ make
Makefile:40: *** falta un separador.  Alto.
```

(sorry for the Spanish :) it says 'missing separator. stop'. Seems like the Makefile is in BSD format? Could you include at least a brief description of the dependencies and compilation instructions?

**Comment by StyXman** [comment]
I just opened #56 :)

**Comment by katef** [comment]
much appreciated!
