### ISSUE TITLE
Is ABNF supported?

### ISSUE THREAD

**Issue by xcurry** [katef/kgt#57]
I downloaded and built `kgt` and then ran this command:

```
./build/bin/kgt -l abnf -e svg < ./examples/abnf.abnf > ./abnf.svg
```

No message and the output length of file abnf.svg is 0. However, expr.bnf to expr.svg works fine. Have not tried other flavours yet.

**Comment by katef** [comment]
ABNF is supported! The parsing there is tripping up on the trailing comments after productions. That's a bug, #11. I'm not sure how to fix it.

Also not giving an error message is a bug.

If you remove the comments, you should see output:
```
; cat examples/abnf.abnf | grep -v ';' | ./build/bin/kgt -l abnf -e svg
```

**Comment by xcurry** [comment]
Will close this as it is already being tracked. The workaround is what I will use in the meantime.

**Comment by katef** [comment]
Thanks for reporting it! sorry it sucks a bit. I think I have to rework how all the whitespace is handled for ABNF, somehow. I'm really not sure :/
